spring.profiles.active=dev
spring.application.name=cris-play
server.servlet.context-path=/cris-play/api

#Spring data JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cris_play_db
spring.datasource.username=cris
spring.datasource.password=cris.proyect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Ollama configuration
langchain4j.ollama.base-url=http://localhost:11434
langchain4j.ollama.model-name=tinyllama
langchain4j.ollama.model.log-requests=true
langchain4j.ollama.model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.langchain4j=DEBUG